version: '3'

services:
###> symfony/mercure-bundle ###
  mercure:
#    ports:
#      - "80"
###< symfony/mercure-bundle ###

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###
